name: Code Quality Checks flake8

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Specify desired Python version

      # Step 3: Install dependencies
      - name: Install project dependencies
        run: |
          echo "Upgrading pip"
          python -m pip install --upgrade pip

          # Install dependencies listed in the requirements.txt
          pip install -r requirements.txt

      # Step 4: Run Flake8
      - name: Running Flake8 check
        run: |
          flake8 src
          echo "Flake8 checks have been executed"
